# Generated by Django 5.0.6 on 2026-08-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('ORDER_PROCESSING', 'Order Processing'), ('ORDER_COMPLETED', 'Order Completed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_REFUNDED', 'Order Refunded'), ('ACCOUNT', 'Account')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
