# Generated by Django 5.0.6 on 2026-08-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_method', models.CharField(choices=[('STEAM_GIFT', 'Steam Gift'), ('STEAM_TRADE', 'Steam Trade'), ('GAME_CODE', 'Game Code'), ('MANUAL_ACTIVATION', 'Manual Activation')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_FOR_PAYMENT', 'Waiting for Payment'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('STEAM_FRIEND_REQUESTED', 'Steam Friend Requested'), ('WAITING_TRADE', 'Waiting Trade'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=32)),
                ('steam_profile_url', models.CharField(blank=True, max_length=200)),
                ('steam_id64', models.CharField(blank=True, max_length=17)),
                ('delivery_data', models.JSONField(blank=True, default=dict, help_text='e.g. issued game code')),
                ('friend_requested_at', models.DateTimeField(blank=True, null=True)),
                ('trade_ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FulfillmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
