# Generated by Django 5.0.6 on 2026-08-19 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='fulfillmentnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fulfillmentnote',
            name='fulfillment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fulfillment.fulfillment'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['status'], name='fulfillment_status_fdcc23_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['assigned_admin'], name='fulfillment_assigne_c31136_idx'),
        ),
    ]
