# Generated by Django 5.0.6 on 2026-08-19 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(help_text='e.g. item, subscription, game_time', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('stock', models.PositiveIntegerField(blank=True, help_text='null = unlimited/digital', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_method', models.CharField(choices=[('STEAM_GIFT', 'Steam Gift'), ('STEAM_TRADE', 'Steam Trade'), ('GAME_CODE', 'Game Code'), ('MANUAL_ACTIVATION', 'Manual Activation')], max_length=32)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/covers/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='games.category')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='games.game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequiredField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(help_text='e.g. steam_profile_url, battlenet_account, region, faceit_username', max_length=64)),
                ('label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('select', 'Select')], default='text', max_length=16)),
                ('is_required', models.BooleanField(default=True)),
                ('validation_regex', models.CharField(blank=True, max_length=300)),
                ('options', models.JSONField(blank=True, help_text='For select fields: list of {value, label}', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields', to='products.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('ar', 'Arabic'), ('ru', 'Russian')], max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "30 Days", "3 Months"', max_length=100)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['game', 'category'], name='products_pr_game_id_5e1eba_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrequiredfield',
            unique_together={('product', 'field_key')},
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('product', 'language_code')},
        ),
    ]
